### ISSUE TITLE
Localization -  Brazil Portuguese (Português Brasil) <pt-br.cfg>  GameData

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/JackOLantern#26]
Localization - ![Brazil Portuguese (Português Brasil)][BR] <pt-br.cfg> 

### GameData

- [ ] add pt-br.cfg  

### Translation

- [ ] [![Português Brasil][BR]][BR] [Brazil Portuguese (Português Brasil)][BR] <pt-br.cfg>  

[BR]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Brazilian-flag-sm.png "Brazil" 

### Update Documentation

- [x]  mod Readme 🔢 
- [x]  releaseNotes.md 🧾 

### GitHub Issues

- [x] assign to zer0Kerbal
- [x] assign projects (user and repo)
- [x] assign label: Localization
- [x] assign label: help-wanted
- [x] assign milestone: Localization - Brazil Portuguese (Português Brasil) <pt-br.cfg>

### Update Social Media

- [x] CurseForge
- [x] CKAN
- [x] Forum
- [x] GitHub
- [x] Patreon
- [x] Reddit
- [x] SpaceDock

### Wiki

- [x] update localization list 
  

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization" 
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

**Comment by zer0Kerbal** [comment]
closes #26

**Comment by zer0Kerbal** [comment]
@lisias

**Comment by lemostrash** [comment]
@zer0Kerbal I have some simple ideas for the readme, can I assign them?

**Comment by zer0Kerbal** [comment]
> @zer0Kerbal I have some simple ideas for the readme, can I assign them?

@lemostrash yes.

**Comment by Lisias** [comment]
Implemented on https://github.com/zer0Kerbal/JackOLantern/pull/64 .

Cheers!
