### ISSUE TITLE
 Localization Norwegian (Norsk) <no-no.cfg>   

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/JackOLantern#31]
Localization - ![Norwegian (Norsk)][NO] <no-no.cfg>  

### GameData

- [x] add <no-no.cfg>  

### Translation

- [ ] [![Norsk][NO]][NO] [Norwegian (Norsk)][NO] <no-no.cfg>  

[NO]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/zed'K/Localization/img/Norwegian-flag-sm.png "Norsk"

### Update Documentation

- [x]  mod Readme 🔢 
- [x]  releaseNotes.md 🧾 

### GitHub Issues

- [x] assign to zer0Kerbal
- [x] assign projects (user and repo)
- [x] assign label: Localization
- [x] assign label: help-wanted
- [x] assign milestone: Localization - [Norwegian (Norsk)][NO] <no-no.cfg>

### Update Social Media

- [x] CurseForge
- [x] CKAN
- [x] Forum
- [x] GitHub
- [x] Patreon
- [x] Reddit
- [x] SpaceDock

### Wiki

- [x] update localization list 
  

[URL:lclztn]: https://github.com/zer0Kerbal/lclztn/blob/master/readme.md "Localization" 
[URL:qs]: https://github.com/zer0Kerbal/lclztn/blob/master/quickstart.md "Quick Start"

**Comment by tplive** [comment]
I can work on this! 🎃
