### ISSUE TITLE
Turkish (Türk) <tr-tr.cfg>

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/JackOLantern#45]
﻿# Localization - ![Türk][TR] Turkish (Türk) <tr-tr.cfg>

## GitHub

* Completed:
  * [x] assign
    * [x] @zer0Kerbal
    * [x] Repo Localization Project
    * [x] Label: type: localization
    * [x] Label: help-wanted
    * [x] hacktoberfest
    * [x] good-first-issue
    * [x] contributions-welcome
    * [x] beginner-friendly
    * [x] Milestone: Localization - Master

### Done by :octocat: contributor

* Some helpful reading
  * [Readme on localization][lclztn]
  * [Quickstart guide to localization][qs]
* GameData (done by contributor)
  * [ ] add Localization\[tr-tr.cfg] 🗃️
* Translation
  * [ ] ![Türk][TR] Turkish (Türk) <tr-tr.cfg>

### below done by @zer0Kerbal

* Update
  * Documentation
    * [x] [readme.md] 🔢
    * [x] [release.md] 🧾
  * docs/
    * [x] docs/[localization.md]
  * Update Social Media
  * [x] GitHub (automated) (zer0Kerbal/zer0Kerbal)
  * [x] CurseForge
  * [x] Reddit
  * [x] Twitter @zer0Kerbal
  * [x] Forum
  * [x] Patreon
  * [x] SpaceDock
  * [x] CKAN (automated)

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"

[TR]: https://raw.githubusercontent.com/zer0Kerbal/zer0Kerbal/master/img/TR.png "Türk"

this file: © All Rights Reserved by@zer0Kerbal

**Comment by havebooze** [comment]
I wanna contribute.

**Comment by havebooze** [comment]
But I can't see anything that I can do. I am new in this. Can you please tell where to check?

**Comment by zer0Kerbal** [comment]
> But I can't see anything that I can do. I am new in this. Can you please tell where to check?

* Some helpful reading
  * [Readme on localization][lclztn]
  * [Quickstart guide to localization][qs]
  * these should help guide you
  * both are in markdown {text}
  * if you are feeling very helpful, kindly translate these as well. ;P
* GameData (done by contributor)
  * [ ] add Localization\[en-us.cfg] 🗃️
* Translation
  * [ ] ![English][EN] English <en-us.cfg>

1. Fork this repo
2. Create a branch name it 'translations' or localizations (suggestions)
3. goto `GameData/JackOLantern/Localization/`
4. copy <en-us.cfg>
5. rename to <tr-tr.cfg>
6. open the file and translate everything to the right of `#??? = `
7. change the `en-us` to `tr-tr`
8. please include an attribution to you in the localization file, something like:
  * `// Translated by: [havebooze](https://github.com/havebooze)`
  * alternatively if you want another name from the KSP forums...
9. when done, PR it and you could reference this issue
10. After it has been merged by me, you may delete your fork.

have fun and thank you! :octocat: 🎃

[lclztn]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/readme.md  "Localization"
[qs]: https://github.com/zer0Kerbal/zer0Kerbal/blob/master/Localization/quickstart.md "Quick Start"
