### ISSUE TITLE
Enabled has become Disabled and vice versa?

### ISSUE THREAD

**Issue by tplive** [zer0Kerbal/JackOLantern#50]
https://github.com/zer0Kerbal/JackOLantern/blob/567f5110d0dd0fa1f3076a208272d11eca8959cb/GameData/JackOLantern/Localization/en-us.cfg#L15
https://github.com/zer0Kerbal/JackOLantern/blob/567f5110d0dd0fa1f3076a208272d11eca8959cb/GameData/JackOLantern/Localization/en-us.cfg#L16
https://github.com/zer0Kerbal/JackOLantern/blob/567f5110d0dd0fa1f3076a208272d11eca8959cb/GameData/JackOLantern/Localization/en-us.cfg#L19
https://github.com/zer0Kerbal/JackOLantern/blob/567f5110d0dd0fa1f3076a208272d11eca8959cb/GameData/JackOLantern/Localization/en-us.cfg#L20

As you can see, string suffixes `*-ena` and `*-dis` are paired with values that have it the other way around.

This is possibly wrong? Or at least confusing? :)

**Comment by zer0Kerbal** [comment]
> https://github.com/zer0Kerbal/JackOLantern/blob/567f5110d0dd0fa1f3076a208272d11eca8959cb/GameData/JackOLantern/Localization/en-us.cfg#L15
> 
> 
> https://github.com/zer0Kerbal/JackOLantern/blob/567f5110d0dd0fa1f3076a208272d11eca8959cb/GameData/JackOLantern/Localization/en-us.cfg#L16
> 
> 
> https://github.com/zer0Kerbal/JackOLantern/blob/567f5110d0dd0fa1f3076a208272d11eca8959cb/GameData/JackOLantern/Localization/en-us.cfg#L19
> 
> 
> https://github.com/zer0Kerbal/JackOLantern/blob/567f5110d0dd0fa1f3076a208272d11eca8959cb/GameData/JackOLantern/Localization/en-us.cfg#L20
> 
> As you can see, string suffixes `*-ena` and `*-dis` are paired with values that have it the other way around.
> 
> This is possibly wrong? Or at least confusing? :)

you are absolutely correct! thank you!
